name: 'semistandard-ga'
author: 'MP3Martin'
description: 'Auto commit with semistandard fix'
inputs:
  args:  # id of input
    description: 'args to semistandard'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}

branding:
  icon: 'check-circle'
  color: 'black'
