name: 'standardjs-ga'
author: 'jopereyral'
description: 'Auto commit with standardjs fix'
inputs:
  args:  # id of input
    description: 'args to standardjs'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}

branding:
  icon: 'check-circle'
  color: 'black'